version: '3'
services:
  api-biblioteca:
    image: api-biblioteca
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
    - bd
    ports:
    - 8087:8080
    volumes:
    - /data/api-biblioteca
  bd:
    image: mysql:latest
    ports: 
     - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=biblioteca
    - MYSQL_USER=app_user
    - MYSQL_PASSWORD=programas
    volumes:
    - /data/mysql
